export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const FETCH_RECIPE_DETAILS_START = 'FETCH_RECIPE_DETAILS_START';
export const FETCH_RECIPE_DETAILS_SUCCESS = 'FETCH_RECIPE_DETAILS_SUCCESS';
export const FETCH_RECIPE_DETAILS_FAIL = 'FETCH_RECIPE_DETAILS_FAIL';

export const ADD_RECIPE_START = 'ADD_RECIPE_START';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAIL = 'ADD_RECIPE_FAIL';

export const FETCH_INGREDIENTS_START = 'FETCH_INGREDIENTS_START';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';

export const ADD_INGREDIENT_TO_RECIPE_START = 'ADD_INGREDIENT_TO_RECIPE';
export const ADD_INGREDIENT_TO_RECIPE_SUCCESS = 'ADD_INGREDIENT_TO_RECIPE_SUCCESS';
export const ADD_INGREDIENT_TO_RECIPE_FAIL = 'ADD_INGREDIENT_TO_RECIPE_FAIL';

export const FETCH_ADDED_INGREDIENTS_START = 'FETCH_ADDED_INGREDIENTS_START';
export const FETCH_ADDED_INGREDIENTS_SUCCESS = 'FETCH_ADDED_INGREDIENTS_SUCCESS';
export const FETCH_ADDED_INGREDIENTS_FAIL = 'FETCH_ADDED_INGREDIENTS_FAIL';

export const ADD_STEP_TO_RECIPE_START = 'ADD_STEP_TO_RECIPE_START';
export const ADD_STEP_TO_RECIPE_SUCCESS = 'ADD_STEP_TO_RECIPE_SUCCESS';
export const ADD_STEP_TO_RECIPE_FAIL = 'ADD_STEP_TO_RECIPE_FAIL';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const AUTHENTICATED = 'AUTHENTICATED';